"""init_db

Revision ID: 004e25c91cca
Revises:
Create Date: 2026-03-23 18:19:08.971357

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from src.application.core.config import settings

# revision identifiers, used by Alembic.
revision: str = '004e25c91cca'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'categories',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('title', sa.String(), nullable=False),
        sa.Column('description', sa.String(), nullable=False),
        sa.Column('is_published', sa.Boolean(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        schema=settings.POSTGRES_SCHEMA,
    )
    op.create_table(
        'locations',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('is_published', sa.Boolean(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        schema=settings.POSTGRES_SCHEMA,
    )
    op.create_table(
        'users',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('username', sa.String(), nullable=False),
        sa.Column('email', sa.String(), nullable=False),
        sa.Column('password', sa.String(), nullable=False),
        sa.Column('first_name', sa.String(), nullable=True),
        sa.Column('last_name', sa.String(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('is_admin', sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('email'),
        sa.UniqueConstraint('username'),
        schema=settings.POSTGRES_SCHEMA,
    )
    op.create_table(
        'posts',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('title', sa.String(), nullable=False),
        sa.Column('text', sa.String(), nullable=False),
        sa.Column('pub_date', sa.DateTime(timezone=True), nullable=False),
        sa.Column('author_id', sa.Integer(), nullable=False),
        sa.Column('location_id', sa.Uuid(), nullable=True),
        sa.Column('category_id', sa.Uuid(), nullable=False),
        sa.Column('image_path', sa.String(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('is_published', sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ['author_id'],
            [f'{settings.POSTGRES_SCHEMA}.users.id'],
            ondelete='CASCADE',
        ),
        sa.ForeignKeyConstraint(
            ['category_id'],
            [f'{settings.POSTGRES_SCHEMA}.categories.id'],
            ondelete='CASCADE',
        ),
        sa.ForeignKeyConstraint(
            ['location_id'],
            [f'{settings.POSTGRES_SCHEMA}.locations.id'],
            ondelete='SET NULL',
        ),
        sa.PrimaryKeyConstraint('id'),
        schema=settings.POSTGRES_SCHEMA,
    )
    op.create_table(
        'comments',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('text', sa.String(), nullable=False),
        sa.Column('post_id', sa.Uuid(), nullable=False),
        sa.Column('author_id', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ['author_id'],
            [f'{settings.POSTGRES_SCHEMA}.users.id'],
            ondelete='SET NULL',
        ),
        sa.ForeignKeyConstraint(
            ['post_id'],
            [f'{settings.POSTGRES_SCHEMA}.posts.id'],
            ondelete='CASCADE',
        ),
        sa.PrimaryKeyConstraint('id'),
        schema=settings.POSTGRES_SCHEMA,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comments', schema=settings.POSTGRES_SCHEMA)
    op.drop_table('posts', schema=settings.POSTGRES_SCHEMA)
    op.drop_table('users', schema=settings.POSTGRES_SCHEMA)
    op.drop_table('locations', schema=settings.POSTGRES_SCHEMA)
    op.drop_table('categories', schema=settings.POSTGRES_SCHEMA)
    # ### end Alembic commands ###
