"""add_images_to_post_and_comment

Revision ID: 6e242cde32a6
Revises: a14d0dc05464
Create Date: 2026-05-23 21:50:09.120031

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


from src.application.core.config import settings

# revision identifiers, used by Alembic.
revision: str = '6e242cde32a6'
down_revision: Union[str, Sequence[str], None] = 'a14d0dc05464'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('images',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('post_id', sa.Uuid(), nullable=True),
    sa.Column('comment_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['comment_id'], ['application.comments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['post_id'], ['application.posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='application'
    )
    op.drop_column('posts', 'image_path', schema='application')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('image_path', sa.VARCHAR(), autoincrement=False, nullable=True), schema='application')
    op.drop_table('images', schema='application')
    # ### end Alembic commands ###
