"""add_is_publiched_to_comment

Revision ID: a14d0dc05464
Revises: 004e25c91cca
Create Date: 2026-05-09 23:06:15.315404

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


from src.application.core.config import settings

# revision identifiers, used by Alembic.
revision: str = 'a14d0dc05464'
down_revision: Union[str, Sequence[str], None] = '004e25c91cca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('is_published', sa.Boolean(), nullable=False), schema='application')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'is_published', schema='application')
    # ### end Alembic commands ###
